version: 2
project_name: geoip-forward-auth
release:
  github:
    owner: jbub
    name: geoip-forward-auth
builds:
  - main: main.go
    binary: geoip-forward-auth
    ldflags: |
      -s
      -w
      -X github.com/jbub/geoip-forward-auth/internal/version.Version={{ .Version }}
      -X github.com/jbub/geoip-forward-auth/internal/version.Revision={{ .Commit }}
      -X github.com/jbub/geoip-forward-auth/internal/version.BuildDate={{ .Date }}
      -extldflags '-static'
    flags: -tags netgo
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
      - 386
archives:
  - id: release
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{.Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md
snapshot:
  version_template: "{{ .Commit }}"
dockers_v2:
  - dockerfile: .goreleaser/Dockerfile
    sbom: false
    images:
      - "jbub/geoip-forward-auth"
    tags:
      - "{{ .Tag }}"
      - "latest"
    labels:
      org.opencontainers.image.created: "{{.Date}}"
      org.opencontainers.image.name: "{{.ProjectName}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.source: "{{.GitURL}}"
    platforms:
      - linux/amd64
      - linux/arm64
    flags:
      - "--pull"
